language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-liferay-theme' ]; then cd .. && eval "mv $currentfolder generator-liferay-theme" && cd generator-liferay-theme; fi
